### ISSUE TITLE
gen event weights and DY AMCNLO sample

### ISSUE THREAD

**Issue by skalafut** [UMN-CMS/cms-WR#11]
The DYJetsToLL inclusive amcnlo sample has events with both positive and negative gen event weights.  To normalize this sample to the integrated luminosity of data using a scale factor of this form:

(cross section of process)*(integrated luminosity of data) / (total number of events in dataset)

the parameter (total number of events in dataset) should be equal to the number of events with positive gen event weight MINUS the number of events with negative gen event weight.  To fix this, a column should be added to configs/datasets.dat which indicates the number of events in each dataset with negative gen event weight.

**Comment by previsualconsent** [comment]
Shouldn't we just store the
(positive events - negative events)
since this number is only used for normalization?

**Comment by previsualconsent** [comment]
closed by a772e43dcdc5b8e5543
