### ISSUE TITLE
Add norm to output from analysis.cpp 

### ISSUE THREAD

**Issue by previsualconsent** [UMN-CMS/cms-WR#17]
instead of weighting the event by luminosity, cross section, and # events
https://github.com/UMN-CMS/cms-WR/blob/master/bin/analysis.cpp#L331
write the value to the root file as "minitreefolcer/norm" alongside "minitreefolder/t"

**Comment by previsualconsent** [comment]
I was thinking about this (remembered that it wasn't done. 
There is already "normalization" in the tree. should we normalization but the lumi and XS weights?

**Comment by skalafut** [comment]
What do you mean by "normalization but the lumi and XS weights"?


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by previsualconsent** [comment]
Sorry I edited it on github.

Should we multiply the normalization in the ttree by the lumi/XS/SF weights
instead of multiplying each event weight by this?

**Comment by skalafut** [comment]
You could do this with the lumi and XS weight, but since the SF weight
changes event by event you would still have to do an event by event weight
when adding events to the RooDataset.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by previsualconsent** [comment]
Okay, sounds good.

**Comment by previsualconsent** [comment]
This doesn't work for powheg where different events can have different cross section weights.
