### ISSUE TITLE
DY Zpeak count scripts

### ISSUE THREAD

**Issue by previsualconsent** [UMN-CMS/cms-WR#18]
Let's make the count of # events in the DY minitrees a standard check we run. 

Commit the script to make the counts and also commit the output of the script lets say in
"config/DYZPeak.dat"
So we can track changes.

**Comment by skalafut** [comment]
sorry for not commenting on this earlier.  This issue was solved along with issue #25 and #27.  Now whenever scripts/wrValidation.sh is run, the event counts in DY minitrees is saved to a file which is tracked in the cmsWR repo.
