### ISSUE TITLE
Rochester cut

### ISSUE THREAD

**Issue by previsualconsent** [UMN-CMS/cms-WR#20]
- implement recommended change, 5 sigma cut on random number distribution

**Comment by jec429** [comment]
Done.

**Comment by shervin86** [comment]
Please don't close the issue by yourself. Put a comment referencing the PR number. It's up to who merge it to close the issue. This is a good practice that helps keep tracking of things.

The PR seems to be fine and merged. I've not tested it, but I supposed you did and have a plot of the random numbers generated before and after the fix.

--
Shervin
Da: jec429
Inviato: mercoledì 27 aprile 2016 15:30
A: UMN-CMS/cms-WR
Rispondi a: UMN-CMS/cms-WR
Oggetto: Re: [UMN-CMS/cms-WR] Rochester cut (#20)



Done.
