### ISSUE TITLE
Final plots with miniTrees

### ISSUE THREAD

**Issue by shervin86** [UMN-CMS/cms-WR#25]
We need a simple script making plots running analysis.cpp
Plots should be put in a directory with the git commit well identified.
Plots are meant for final AN and also as validation of each production. It's a crucial instrument to make sure that whenever a new version of the code is deployed, it produces consistent results.
The script should also run on the miniTrees and dump in a txt file the number of events for each tree. This a very quick check on the sanity of the miniTree production and validation of the code.

**Comment by jec429** [comment]
We have been using miniPlotter.C which runs on the outputs of analysis.cpp and can be modified to produce the desired txt files.

**Comment by skalafut** [comment]
Peter Hansen has already written a script, miniTreeDumpCheck.py, which runs over all existing minitrees in a predefined location (default is Shervin's CERN eos space) and writes the number of events in each minitree to a txt file.  I will make one script to run analysis.cpp, then miniPlotter.C and miniPlotterForDYTandP.C to make plots, and finally Peter's miniTreeDumpCheck.py to check the miniTree event counts.
