### ISSUE TITLE
Fix fit normalization

### ISSUE THREAD

**Issue by previsualconsent** [UMN-CMS/cms-WR#35]
The normalization of the fit doesn't match the normalization stored in tf1 of analysis.cpp

**Comment by skalafut** [comment]
In analysis.cpp there is a tree named tf1 which saves the results of an exponential fitted to the M_LLJJ distribution, including the exponential fit parameter, the normalization of the fit, and the number of weighted events in the M_LLJJ distribution above 600 GeV.  Previously the normalization of the fit was equal to the number of weighted entries in the entire M_LLJJ distribution, including entries with M_LLJJ below 600 GeV.  Analysis.cpp has been updated in PR 43 to calculate the fit normalization as the number of weighted entries in the M_LLJJ distribution above 600 GeV.
