### ISSUE TITLE
Unusual loss of EMu events in TTBar minitrees. 

### ISSUE THREAD

**Issue by previsualconsent** [UMN-CMS/cms-WR#37]

**Comment by skalafut** [comment]
resolved with PR 41

**Comment by shervin86** [comment]
The issue can be closed only once the corresponding PR is merged. Can you spend a couple of minutes to write in words what is the problem and how the changes are supposed to fix it?

--
Shervin
Da: skalafut
Inviato: giovedì 5 maggio 2016 19:05
A: UMN-CMS/cms-WR
Rispondi a: UMN-CMS/cms-WR
Oggetto: Re: [UMN-CMS/cms-WR] Unusual loss of EMu events in TTBar minitrees. (#37)



Closed #37<https://github.com/UMN-CMS/cms-WR/issues/37>.

**Comment by skalafut** [comment]
I will write the description of the problem and solution in the issue.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by skalafut** [comment]
In test/runAnalysis_cfg.py, there is one path which is responsible for creating and filling the flavoursideband minitree for each dataset processed by runAnalysis_cfg.py.  This path, named FlavourSideband, is defined on line 156 of runAnalysis_cfg.py.  Previously this path required the filter signalRegionFilter to return false in order for an event to be selected by the FlavourSideband path.  signalRegionFilter returns true if at least one dilepton candidate made from two electrons or two muons is found in an event with dilepton mass above 200 GeV.  Thus, requiring that signalRegionFilter return false was restricting the FlavourSideband path to events which were subjected to di-electron OR di-muon kinematic requirements.  The FlavourSideband path should only require that at least one unique mu-ele pair be found with dilepton mass > 200 GeV.  PR 41 fixes this problem by removing signalRegionFilter from the FlavourSideband path defined in test/runAnalysis_cfg.py.

**Comment by previsualconsent** [comment]
Found issue with the flavourSidebandSelection string missing ()
