### ISSUE TITLE
How to incorporate statistical uncertainties for DY/TTBar in datacards?

### ISSUE THREAD

**Issue by previsualconsent** [UMN-CMS/cms-WR#38]

**Comment by previsualconsent** [comment]
Add varying fits within uncertainties in analysis.cpp
This should be done on central value fits.

**Comment by previsualconsent** [comment]
Added this commit:
https://github.com/UMN-CMS/cms-WR/commit/05a01e80a63e5b28f0726b89ce441966e8ac4215

I think the stat uncertainty and the systematics should both be calculated in the same run of analysis.cpp since they are stored in separate trees. If #28 is completed, I will rebase this commit onto that PR and make sure loop one does central values + statTree and subsequent loops will be 
still need to add to combineTools properly.

**Comment by skalafut** [comment]
Hi Peter:

PR #28 has not been completed yet, we are waiting for electron energy
smearing to be implemented by Shervin.  The stat uncertainty should be
calculated once without systematics to understand the magnitude of the stat
uncertainty, and facilitate comparisons between the stat uncertainty and
other uncertainties.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by previsualconsent** [comment]
Yes, exactly. I just don't want to have to run analysis once for syst and
once for stat. Both can be calculated. So loop 1 will do central value and
then calculate stat unc. Then each subsequent loop will be a toy for syst
unc.

I don't like nToys==1 as the flag for central value as it means we can't do
both uncertainties.

**Comment by skalafut** [comment]
Understood.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by rchatter** [comment]
Hi Peter and Sean,

As I see in analysis.cpp we dont have a do_Systematics options.
Sean can correct me if I'm wrong but to evaluate systematic uncertainties
we we choose nToys >> 1.
So are you suggesting something along these lines that maybe we add in the
boost options a do_Syst flag, such that do_Syst= 0 would automatically take
nToys = 1 and evaluate the central values and doSyst = 1 would take some
default number of toys(maybe 500) and in the first throw evaluate the stat.
errors and then systematics.

Are you guys thinking along these lines?

thanks,
Rajdeep

On Tue, May 10, 2016 at 8:18 AM, Peter Hansen <notifications@github.com>
wrote:

> Yes, exactly. I just don't want to have to run analysis once for syst and
> once for stat. Both can be calculated. So loop 1 will do central value and
> then calculate stat unc. Then each subsequent loop will be a toy for syst
> unc.
>
> I don't like nToys==1 as the flag for central value as it means we can't do
> both uncertainties.
>
>
> On Tue, May 10, 2016, 03:44 skalafut <notifications@github.com> wrote:
>
> > Hi Peter:
> >
> > PR #28 has not been completed yet, we are waiting for electron energy
> > smearing to be implemented by Shervin. The stat uncertainty should be
> > calculated once without systematics to understand the magnitude of the
> stat
> > uncertainty, and facilitate comparisons between the stat uncertainty and
> > other uncertainties.
> >
> >
> > Regards,
> > Sean Kalafut
> >
> > Physics PhD candidate
> > University of Minnesota Twin Cities
> >
> > On Mon, May 9, 2016 at 7:00 PM, Peter Hansen <notifications@github.com>
> > wrote:
> >
> > > Added this commit:
> > > 05a01e8
> > > <
> >
> https://github.com/UMN-CMS/cms-WR/commit/05a01e80a63e5b28f0726b89ce441966e8ac4215
> > >
> > >
> > > I think the stat uncertainty and the systematics should both be
> > calculated
> > > in the same run of analysis.cpp since they are stored in separate
> trees.
> > If
> > > #28 <https://github.com/UMN-CMS/cms-WR/pull/28> is completed, I will
> > > rebase this commit onto that PR and make sure loop one does central
> > values
> > > + statTree and subsequent loops will be
> > > still need to add to combineTools properly.
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/UMN-CMS/cms-WR/issues/38#issuecomment-217923918>
> > >
> >
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/UMN-CMS/cms-WR/issues/38#issuecomment-218095215>
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UMN-CMS/cms-WR/issues/38#issuecomment-218154245>
>



-- 


Rajdeep.Mohan.Chatterjee
Post Doctoral Fellow
School of Physics and Astronomy
University of Minnesota
115 Union Street Street SE
Minneapolis MN 55455
USA

**Comment by rchatter** [comment]
Hi Rajdeep:

Absolutely, to evaluate the systematic uncertainties we run analysis.cpp
with nToys > 500 (or more).  The central values for smearing need to be
calculated in one run of analysis.cpp with ntoys = 1.  What you describe as
"doSyst = 1" is precisely what Peter is thinking (and only now I am fully
appreciating his suggestion).


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities
