### ISSUE TITLE
DY scale factors

### ISSUE THREAD

**Issue by skalafut** [UMN-CMS/cms-WR#44]
calculate DY data/MC scale factors, save them to a txt file which is tracked by the repository, and read the scale factors into analysis.cpp and use them when processing any DY minitrees.

**Comment by previsualconsent** [comment]
Did we ever include the uncertainties for these in the config? Are the uncertainties included in the datacard or by the toy thrower.

**Comment by skalafut** [comment]
No I will add those tonight, it's a simple addition.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities

**Comment by previsualconsent** [comment]
So, the second question? Are the uncertainties included in the datacard or by the toy thrower?

**Comment by skalafut** [comment]
Oh sorry, I misinterpreted your question.  Currently these uncertainties
are not included in the toy thrower, nor are the values even saved in
dyScaleFactors.txt.  I don't think we need the degree of customization
provided by toy thrower for these uncertainties, so we can add them to the
datacard.

Peter can you remind me where are the instructions to run the limit setting
code?  I will likely need to calculate limits on Sunday and Monday with
systematics.


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities
