### ISSUE TITLE
Remove Rochester from MiniTTree production

### ISSUE THREAD

**Issue by jec429** [UMN-CMS/cms-WR#47]
Rochester corrections now moved to analysis.cpp to avoid seed problems with the job splitting.

**Comment by rchatter** [comment]
Hi Jorge,
I understand the removal of Rochester from miniTree production, but didn't
we decide to have Rochester applied from within the ToyThrower.

thanks,
Rajdeep

On Mon, May 9, 2016 at 12:38 PM, jec429 <notifications@github.com> wrote:

> Rochester corrections now moved to analysis.cpp to avoid seed problems
> with the job splitting.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/UMN-CMS/cms-WR/issues/47>
>



-- 


Rajdeep.Mohan.Chatterjee
Post Doctoral Fellow
School of Physics and Astronomy
University of Minnesota
115 Union Street Street SE
Minneapolis MN 55455
USA

**Comment by jec429** [comment]
That is right. Rochester corrections will be applied from within ToyThrower, so I just changed the collection that is used during miniTree production to be just the isolated tuneP muons instead of the scaled corrected muons that included the Rochester corrections.

**Comment by rchatter** [comment]
thanks Jorge.

On Mon, May 9, 2016 at 1:31 PM, jec429 <notifications@github.com> wrote:

> That is right. Rochester corrections will be applied from within
> ToyThrower, so I just changed the collection that is used during miniTree
> production to be just the isolated tuneP muons instead of the scaled
> corrected muons that included the Rochester corrections.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/UMN-CMS/cms-WR/issues/47#issuecomment-217948812>
>



-- 


Rajdeep.Mohan.Chatterjee
Post Doctoral Fellow
School of Physics and Astronomy
University of Minnesota
115 Union Street Street SE
Minneapolis MN 55455
USA

**Comment by shervin86** [comment]
Comments in the PR #48.
Issue already fixed in master
