### ISSUE TITLE
DYToEE cross-sections

### ISSUE THREAD

**Issue by jec429** [UMN-CMS/cms-WR#5]
All the DYToEE datasets have the cross-section corresponding to DYToEE_50_120.

**Comment by jec429** [comment]
Also
DYToMuMu_powheg_1400to2300	 ...	2.737e+00
is wrong.

**Comment by shervin86** [comment]
can you check if this is fixed in the master branch and close the issue?

**Comment by shervin86** [comment]
@jec429  can you double check if the cross-sections are fine?

**Comment by jec429** [comment]
I can fix the cross-sections, but I am not sure how we handle the fact that the DY AMCNLO event count should be weighted. It would be nice to have another column in the dataset file with this weight and the config reader take into account.

**Comment by shervin86** [comment]
Now there is a script that looks at the number of events read by CRAB when making the skim and saves that number. One should instead save the weighted sum of events. I would suggest to right a small analyzer that we can add in the skimming sequence and that prints the weighted sum of events to the stdout or a producer that saves such a number in the per-run-collections (more complicated, but safe). We should think more about that.

--
Shervin
Da: jec429
Inviato: lunedì 2 maggio 2016 19:03
A: UMN-CMS/cms-WR
Rispondi a: UMN-CMS/cms-WR
Cc: Shervin Nourbakhsh; Assign
Oggetto: Re: [UMN-CMS/cms-WR] DYToEE cross-sections (#5)



I can fix the cross-sections, but I am not sure how we handle the fact that the DY AMCNLO event count should be weighted. It would be nice to have another column in the dataset file with this weight and the config reader take into account.

**Comment by jec429** [comment]
That sounds like a good idea. I will fix the cross-sections in the meantime.

**Comment by previsualconsent** [comment]
assuming fixed
