### ISSUE TITLE
Fix reading SF from file every single event. 

### ISSUE THREAD

**Issue by previsualconsent** [UMN-CMS/cms-WR#52]
This line
https://github.com/UMN-CMS/cms-WR/blob/master/bin/analysis.cpp#L470
opens a text file and reads the same number once per event. Should be once per dataset.

**Comment by skalafut** [comment]
Yes, unfortunately we are doing the same silly game with the lumi*Xsxn
weight and the data/DY MC weight.  Both only need to be read once per
dataset, but when I implemented the data/DY MC reweighting in analysis.cpp
the simplest way was to add an extra multiplicative factor to the weight
which is calculated for every event.

Peter do you see a better way to do this, such that the file
dyScalingFactors.txt only needs to be read once per dataset?


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities
