### ISSUE TITLE
add uncertainties to configs/dyScaleFactors.txt

### ISSUE THREAD

**Issue by skalafut** [UMN-CMS/cms-WR#59]
The scale factors saved in configs/dyScaleFactors.txt should have uncertainties associated with them.  Add these uncertainties in a separate column.

**Comment by previsualconsent** [comment]
i'm pretty sure this was done.

**Comment by skalafut** [comment]
yes it was


Regards,
Sean Kalafut

Physics PhD candidate
University of Minnesota Twin Cities
